apiVersion: v1
kind: Service
metadata:
  name: kube-ciserver
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: console
  - port: 50000
    targetPort: 50000
    name: api
  selector:
    app: kube-ciserver